### ISSUE TITLE
Buenos Aires

### ISSUE THREAD

**Issue by raynamharris** [carpentries/2018-04-bug-bbq#2]
Organization: R Ladies Buenos Aires
Location: TBD
Lat/Lon: 34.6037° S, 58.3816° W
Date/Time: Thursday, April 12 (times TBD)
Contact Person: Rayna Harris
Contact information: rayna.harris@gmail.com

Will update the location in a few days

**Comment by fmichonneau** [comment]
awesome! I added it to the website. I'll keep the issue open until you send me the update for the location and times

**Comment by raynamharris** [comment]
@fmichonneau Here's the updated location. 


[valo hublab](https://valohublab.com/), Av. Alicia Moreau de Justo 1750, Buenos Aires

**Comment by fmichonneau** [comment]
Great, thanks! Do you know the start/end times?

**Comment by raynamharris** [comment]
6:30 pm - 9:30 pm ART (or 5:30 pm - 8:30 pm EST)

**Comment by fmichonneau** [comment]
Very exciting! thanks!
