### ISSUE TITLE
Toronto

### ISSUE THREAD

**Issue by mbonsma** [carpentries/2018-04-bug-bbq#4]
- University/Organization: UofT Coders, University of Toronto
- Location: MADLab, Gerstein Science Information Centre room B112, 9 King's College Circle, Toronto, ON 
- GPS coordinates (latitude, longitude): 43.662195, -79.3961537
- Date and time of the event: April 13, 9 AM ET to 2 PM ET
- Contact Person: Madeleine Bonsma-Fisher (@mbonsma)
- Contact information (email address or website): uoftcoders@gmail.com

**Comment by fmichonneau** [comment]
Awesome! Thanks!
I added you to the site; it might take a few minutes before the site is regenerated and you show up there.
I'm looking forward to seeing your contributions to the Bug BBQ!

**Comment by QuLogic** [comment]
The site says Thursday 13, but should be Friday 13.

**Comment by fmichonneau** [comment]
thanks for catching this! I just fixed it.
